[package]
name = "pallet-ics20-transfer"
version = "4.0.0-dev"
authors = ["Octopus Network <hi@oct.network>"]
edition = "2021"
homepage = "https://github.com/octopus-network"
license = "Unlicense"
publish = false
repository = "https://github.com/octopus-network/substrate-ibc"
description = "FRAME pallet ibc protocol ics20 token transfer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# substrate crates
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
frame-benchmarking = {  default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
frame-support = {  default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
frame-system = {  default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
hex = { version = "0.4.0", default-features = false }
ibc-support = { version = "0.1.0", default-features = false, path = "../../support" }
log = { version = "0.4", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-io = {  default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-runtime = {  default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
primitive-types = { version = "0.12.0", default-features = false, features = ["serde_no_std"] }

ibc = { version = "0.28.0", default-features = false, features = ["parity-scale-codec", "serde"] }
ibc-proto = { version = "0.25.0", default-features = false, features = ["parity-scale-codec"] }


# [target.wasm32-unknown-unknown.dependencies]
# getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
chrono = "0.4.19"
frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
hex = '0.4.0'
pallet-assets = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
pallet-babe = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
pallet-balances = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
pallet-ibc = {default-features = false,  path = "../../core" }
pallet-timestamp = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
# serde = "1.0.142"
# serde_json = { version = "1.0" }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }

sha2 = '0.10.2'
sp-core = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-io = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-keyring = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-runtime = {default-features = false,  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
sp-version = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-benchmarking?/std",
  "frame-support/std",
  "frame-system/std",
  "hex/std",
  "ibc-support/std",
  "log/std",
  "scale-info/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "primitive-types/std",
  "ibc/std",
  "ibc-proto/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
